# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "rXNLASupVQ+buc1PKB57I/hiPINY9l1B7Oh88wFB1D5Z1Vjyn4Lx0hLr+f91tIOL5IAGOvRLBuHakghbL3JvHTdHHqiGTQx1pThxw35EK5eny513kX64qZA8DHZ8e2qY2r5Rjrhm1iw2ZE+d6ghJHKZMk6h/biaVWGOo0xYEubuvHuDrq9yLstCvrHId4JsFtLx8VPcy5g693D2lkc13X9JiI6JfE9V5/YGhfEaIwgCaXO9NOOsH3hja/dt1JkyQSW0eVQcM0XZcmsWHBJSnK2tWDy8NMlCSEgEw11nIJv00jkmljOTQg8iFCZ6ROE/INyvxYjh2N0JVSMQYdqLGtZoyJPdJ0uv8GJXeNRxH8myHsi9V0RpAptMNREXAPoXAnp5Wr7zaJ/N1pJRXzE/iNBLXaVSHm8v9IRMzJ/YCeExsKVXzzejW0RNIhsuHkxSj20Nt3JMAAQY7CuQ5XJcajzeC9cO1zGQCt8kq3zPLT7KU1ZSKemoE3sQXYpKrlAzXHhIAGbFSmSrZfvoNyS+CWYkSKOE6YNO2HoYSY9UYMHRifeMi7WDGKRKjzVdpOjzL/GynDwW/0werlVKYIPJGHcL217gGaiy60Rh4UxrRKqUjPp+EZOfqTA9hLjCCdZsDB1T0N2MJlXzQq3BclC7onaxezy9J6NoP2vtnM+sAeGc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
