travis:
  secure:
    BINSTAR_TOKEN: NGZCoT+yt2WsqjyViwbDe8ZjZ6NoeopYTQXVxdqZJd2deKxoO02MVdQfFoiW/t/n+dCUbQflewBftF6Sn60A7UMbjQsHCkdF43lHclcRat1PFCNhve/wdtmuGmDUcZHPPpxN/6uFlBn39UOTTWv1a1PTxx9mnGpWrxmnoG4Qe4THP2Glm6ZJ3TRRkUimcUiw3HRd+0hYF4FP/UUHPGf58pS01ITcBHIY+hm3B76LXS2RN3e2jWVsnMAgCeoaflbMB2bv2tjEiue5Sxt1KEqYhaU1yo0MgFt5kbjRXxcIs+X3KGpASJ+EUO/xwkqFO/dKARlW2Dav9UKITKaSueq/0x84teUyB8aC0iJDl3VW2BRgIWHAKb6wFk6qFv0nl3BO9MN/iWgnFTTXZONMcgOA6kVkE8/hU43VqISnZ5mjrtegOPtxdWkUdEC2p2T60KCDhH55N9Lmup4EVmT1VBviQ4s60CmXMdNS4MA9+KBBadyXEtwUsIgnTbkCAMJy5/IS+yHcVUGfq4j/LgYDNs6sVDhEkaZzD3OsZbGfNhnZ9HZH5seoZKhyOEgLd3r/C14TdUY1j26YufqsTSqyHRp2SV4fsOJGmeD4vxlR7hRWy4I8gQPl8H72eCHRQWu8X+2fNHTcSZj+bj9WZQi60PHSL4taoEJ1XQrz23Krr2ydCAA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
