travis:
  secure:
    BINSTAR_TOKEN: mcDZQlIifT7fgdQuiBBiwrXeRZ9F1GrfOiZzI5Q1VggtTBFEnmGl61jU7kROcY4XHwUN8AXVU3Hhp1BUdIIZtzbBrEf362FmOKVDkFlcw9Mgn7gLD2IwfNuBrzYwHqS9X6GLCtB3LQXXWx/UevjadmsY1WgD5aMeqCMbdy1VA8953OzuDwe7K6a78YJSnHYcXlP+IQmih12/Y0vnDm6IteIMR02THSgHVnjpFsn0eI91RQOp4uodJZ/ainroYFtyfPtpaOg7NciD1TT8PZ1GZRUOQ6YqVLftqjonKe9x0pzaPNE4+jWIT4K9KxXTF5blBny4kH/OKgIwvxfUvTy1ULPRy2QdJq8cLDgBbz/y60nYA8TcAIWi8KlE2kvJHBZvQHd9jQTqZ6xK1/r/clsI+2vYlPz6oWwZZzGWMFY+kqItIz8RQ7iL7h3VSsBxu9iYrFQVR5tSfNJO1u7HNLhUSn1EQPFi9DyDe1NkYna16nX8quVeyre7ZxVWBZ8AkLS7rRqHLk2JsU2Bob+RE9J0UqQnNWFhoyoN1V0to+Fj8qvltWF7nXtqFfhoBVjxtYaj3fxi169SiPD488uhSz3czyDB2PF8xwiWeV0ch0ILneEYqqB4mvqofQJHPr6XL9dUf2+EgbW4q77q+n1v1b2bw8LC7/dDza9sEJf1XtXVp88=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
