travis:
  secure:
    BINSTAR_TOKEN: ZIh7Ykm+grTd0moydBMjemk0W3zL7GYMqe66u101QCsX4Z7UFsC24C1jozsmLgq0nHm+eK9ik43owWsr555jjwW7xZRB032vXyBgdCkVqHfG3mraADh1xsz3rAH5FdOVY8i+jnkMaoGEl7F/o/BncdPI1X3+IGOnYghHln9wzk7eYm9AQRSumx/1cE4gQtKlpXjL4p0mxehHDzQ1rttJpZdb3sjHx5DAAdZqpcMeSQU0FrAeL6u8rxuIT58XXjDKO1H+cMgT3qiS7iaKKTkygGea0hAUqfvfRaS4Y3ZRQW3rbiY4TvzY/XnAG1F9TTZU/qX5Sj14ILf/dxpcT1umLd/9kaoTAYSvtqxEv72IffcR7IDfr93x/myWECnlKjQO5d6uTkypB9ATFNDVD1kRPl6s+z07/OLt5ul9efKC2fqGd5k2ZyKJ/8zht5OXX9/jp4nZKeWe9liGEIQLmdrxINOLaXrA1URfbA9KhQnNSMXwW1qjfRcBxHSuFJ9z9p7x3wtnd4gyf9AhvKkdvPqNnkwGhNkpyLL4rQvtp7UhWU1c984yLbSC6jrfTpkCI5OHi2gLFH3Y6nHkPBDQUGL2IlonIVeBXh7zXR2GYvAo+ReFgp7NfDC6qVDrEs2wuhlaEERjwqJ737iXyi4xaX/VisJX/Smzm6s2xY+ONrxVRBk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
